### ISSUE TITLE
wake on wireless lan

### ISSUE THREAD

**Issue by uronito** [gw-wiscon/homebridge-philipstv#2]
Hi,

I just discovered that to work properly the function of WOL in models 2014 or higher , would have to add the module wake on lan and when the function of power on launches first have to make a wol the WiFi Mac address and then launch the function as power on this , but does not work well . Therefore should add the module wake on lan and first wol command to launch the IP address and then the function wifi poweron.

Thanks

**Comment by uronito** [comment]
After launching the wol would have to pause 3 seconds

**Comment by gw-wiscon** [comment]
Can you point me to some documentation?

**Comment by uronito** [comment]
ther isn't Docs . I 've learned with my tv testing and modifying its plugin

**Comment by uronito** [comment]
hi,

the last version 0.3.38 is very well, but between  the WOL function and poweron function  should be a pause of 3 seconds.

Thanks.

**Comment by gw-wiscon** [comment]
I have added a WOL function, don't know if it works.
Please test.

**Comment by uronito** [comment]
i have tested, is perfect but between the WOLrequest  function and poweron function (httprequest) should be a pause of 3 seconds. 

this 3 seconds are for system background will ready and can procces httprequest

Thanks

**Comment by uronito** [comment]
I 've learned something new .
if you send a request to the address 192.168.1.132:1925/5/powerstate ( philips tv ip). There may be two answers or unanswered.
If the answer is "standby" or no answer on the TV is off. if the answer is "On" The TV is on .

**Comment by gw-wiscon** [comment]
Will check the time-out thing tomorrow, in principle the socket time-out schould be sufficient.

With respect to the /powerstate method, can you sent me examples of the responses?

**Comment by uronito** [comment]
Hi, 

the answers are:

{"powerstate":"Standby"} ----------> The Tv Is in Standby mode (off) .Accept httprequest for power on

{"powerstate":"On"}--------> The tv is on.

no response---------> The Tv is off. Wol request change this state to {"powerstate":"Standby"} after 4 seconds.

The request is: http://(iptv)/5/powerstate

the method is get, is only for know the state of the tv

Thanks

**Comment by uronito** [comment]
Hi,

Last version 0.3.42 crash on timer settimeout

tanks

**Comment by gw-wiscon** [comment]
You are fast!!

**Comment by uronito** [comment]
;) , jejeje. 
We get the perfect plugin

**Comment by gw-wiscon** [comment]
Should work now

**Comment by gw-wiscon** [comment]
and added support for the powerstate API

**Comment by uronito** [comment]
the plugin works well,

but the tv only gets mode standby , i have incremented timeout to 13000 ms but still dont change powerstate to on

i 'm istudying why

**Comment by gw-wiscon** [comment]
Did you enable quick start?
HOME > [Setup] > [TV settings] > [General settings] > [Quick start]

**Comment by uronito** [comment]
ohhhhh yeahhhhh 

settimeout 16000ms!!!!!!!!!!!!! oh my god!!!!!!!!

Just missing when the TV return the Standby state only the httprequest launched and if no response was launched wol and then httprequest

The 2014 onwards dont have this option

**Comment by uronito** [comment]
my remote app philips Also it takes long to turn on the tv

**Comment by gw-wiscon** [comment]
changed it into an attempt loop

**Comment by gw-wiscon** [comment]
it simply sends upto 8 times a power up request

**Comment by uronito** [comment]
Ohhhhhh yeahhhhhh

The plugins runs perfectly!!!!!!!!!!!!!!!!

You are a crack!!!!!!!!!!

**Comment by uronito** [comment]
thankssss!!!!!!!!!!!!!

**Comment by gw-wiscon** [comment]
yw, I assume I can close the issue now.

**Comment by gw-wiscon** [comment]
Did a small change, can you please retest
Also test the OFF function

**Comment by uronito** [comment]
Echostunreach sometimes in wol and httprequest

**Comment by uronito** [comment]
sometimes tv on sometimes in standby

**Comment by uronito** [comment]
Wait a minute, the tv had remained hanging , I 'm resetting , wait and tell

**Comment by gw-wiscon** [comment]
My understanding sofar is this:

Apperently, your TV has 3 modes:
- OFF
- Standby
- ON

From On to Standby:
- POST /input/key,  body: {key:Standby}

From OFF to StandBy:
- WOL

From Standbye to On:
- POST /input/key,  body: {key:Standby}

Correct?

**Comment by uronito** [comment]
It seems that the plugin works well , I reset the tv and everything ok .

Yes, what you say is correct

From OFF to StandBy:

WOL

I just discovered these commands now

From On to Standby:

http://iptv/5/powerstate
POST /powerstate , body: {powerstate:Standby}

From Standbye to On:
http://iptv/5/powerstate
POST /powerstate, body: {powerstate:On}

**Comment by uronito** [comment]
0.3.52 runs perfectly

**Comment by uronito** [comment]
0.3.56 runs sometimes 

sometimes turn on sometimes no

sometimes turn off sometimes no

most times it works fine, but sometimes fails to turn on and off and to check the state

**Comment by uronito** [comment]
I've been testing a few hours plugin and it seems to work perfect. The only thing is that when the TV returns the "Standby" state, Homebridge should mark the off state. When a httprequest is done to know the status of the TV if it returns "standby" Homebridge should change the check  status to off.

Thanks

**Comment by gw-wiscon** [comment]
I am sorry, veru busy right now.
Will take a look tomorrow evening.

**Comment by uronito** [comment]
Ok, don't worry

Thanks

**Comment by uronito** [comment]
i make a new pull request.

Now Runs Perfect!!!!!!!

Thanks

**Comment by uronito** [comment]
hi gw wiscon

0.3.58 runs perfect!!!!!!

Thanks !!!!!

**Comment by gw-wiscon** [comment]
please test, I added the code.
Thanks again

**Comment by uronito** [comment]
0.3.58 runs Perfect.

but  If the TV is unplugged and turn on in Homebridge , if  can not find the TV should return the status of the TV off in the poll status homebridge. Setpowerstate --- Status poll context should be off

In the onkyo plugin could be the same.

excuse me for my poor english

Thanks

**Comment by uronito** [comment]
I have made a new pull request.

Thanks!!!!!!!

**Comment by uronito** [comment]
0.3.59 the same that 0.3.58.

works perfectly but If the TV is unplugged and turn on in Homebridge , if can not find the TV should return the status of the TV off in the poll status homebridge. Setpowerstate --- Status poll context should be off.

I have made a pull request with a modification, i test and work well.

Thanks

**Comment by gw-wiscon** [comment]
Hi Uronito,

In principle, the set routine is called from the hap-nodejs setValue (see below).
Your solution, was to call this method again, this time with the context set, to avoid that the whole operation start again.

What then happens is in a situation where the power on function fails:
- setValue
-  set function of the philipstv plugin
-    Request WOL, etc
-      Hap-nodejs setValue --> set this.value to false, send change event
- back in setValue
-   Set the newValue to true, send change event

But, if an error is returned, the value is unchanged, and no update is sent along.
This is why I decided to return an error.

Now, I am unsure about the reaction of HomeKit, it might be that the device is shown as ON.
In that case, we still need also to add your proposed change.
So, on paper, it is not required.

I hope this helps.

```
Characteristic.prototype.setValue = function(newValue, callback, context) {

  if (this.listeners('set').length > 0) {

    // allow a listener to handle the setting of this value, and wait for completion
    this.emit('set', newValue, once(function(err) {

      if (err) {
        // pass the error along to our callback
        if (callback) callback(err);
      }
      else {
        // setting the value was a success; so we can cache it now
        var oldValue = this.value;
        this.value = newValue;
        if (callback) callback();

        this.emit('change', { oldValue:oldValue, newValue:newValue, context:context });
      }

    }.bind(this)), context);

  }
  else {

    // no one is listening to the 'set' event, so just assign the value blindly
    var oldValue = this.value;
    this.value = newValue;
    if (callback) callback();

    this.emit('change', { oldValue:oldValue, newValue:newValue, context:context });
  }
```

**Comment by uronito** [comment]
hi gw wiscon,

thanks for your answer.

0.3.65 still show on if tv is unplugged.

the plugin don't check state of the tv. if launch homebridge and the tv is on homebridge dont show "on" state. i belive in this version don't polling state.

Thanks

**Comment by gw-wiscon** [comment]
I believe it always require a polling mode.
Since it does not sent any event by itself when it is switched ON or OFF.
So, if switched ON by using the remote, will stay undetected if polling mode is OFF.

I moved the callback to the beginning of the OM procedure - to improve homekit responsiveness during the procedure

**Comment by uronito** [comment]
You've got it

wowwwww!!!!!!

The plugin works perfect.

Thanks!!!!

**Comment by gw-wiscon** [comment]
I am happy you are set.
Thanks for the nice cooperation, hopefully others will find this plugin usefull also.

**Comment by uronito** [comment]
Thank you so much for everything

2016-02-08 21:25 GMT+01:00 gw-wiscon notifications@github.com:

**Comment by gw-wiscon** [comment]
YW
